## 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [1]:
import pandas as pd
import numpy as np
from selenium.common.exceptions import NoSuchElementException
import time
# Importing selenium webdriver 
from selenium import webdriver

#Importing requests
import requests

# importing regex
import re

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
# Activating the chrome browser
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)

# Opening the homepage of Amazon.in
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

time.sleep(2)

In [31]:
#Make empty lists
Rank = []   
Name = []
Artist = []
Upload_date = []
Views = []


try:
    rnk = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]")
    for i in rnk:
        Rank.append(i.text.split('.')[0])
        Rank = Rank[:30]
except NoSuchElementException:
    Rank.append('-')
time.sleep(1)
try:
    Nam = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]")
    for i in Nam:
        Name.append(i.text.split('[')[0])
        Name = Name[:30]
except NoSuchElementException:
    Name.append('-')    
time.sleep(1)
try:
    Ast = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]")
    for i in Ast:
        Artist.append(i.text)
        Artist = Artist[:30]
except NoSuchElementException:
    Artist.append('-')    
time.sleep(1)
try:
    date = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]")
    for i in date:
        Upload_date.append(i.text)
        Upload_date = Upload_date[:30]
except NoSuchElementException:
    Upload_date.append('-')    
time.sleep(1)
try:
    Vws = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]")
    for i in Vws:
        Views.append(i.text)
        Views = Views[:30]
except NoSuchElementException:
    Views.append('-')    
time.sleep(1)
# Make dataframe
prod_df = pd.DataFrame({'Rank':Rank,'Name':Name,'Artist':Artist,'Upload_date':Upload_date,'Views(Billion)':Views})
prod_df.head(5)

,Rank,Name,Artist,Upload_date,Views(Billion)
0,1,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.21
1,2,"""Despacito""",Luis Fonsi,"January 12, 2017",7.75
2,3,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.17
3,4,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.62
4,5,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.42

### 2) Scrape the details team Indiaâ€™s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [37]:
# Activating the chrome browser
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)

# Opening the homepage of Amazon.in
url = "https://www.bcci.tv/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [39]:
international_button = driver.find_element_by_xpath("/html/body/nav/div/div[2]/ul[1]/li[2]/a")       # Locating search_button by xpath
international_button.click()# Clicking the button to start search

In [47]:
#Make empty lists
Match_title = []   
Series = []
Place = []
Date = []
Time= []


try:
    match = driver.find_elements_by_xpath("//span[@class='matchOrderText ng-binding ng-scope']")
    for i in match:
        Match_title.append(i.text.split('-')[0])
except NoSuchElementException:
    Match_title.append('-')
time.sleep(1)

try:
    ser = driver.find_elements_by_xpath("//span[@class='ng-binding']")
    for i in ser:
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
time.sleep(1)

try:
    place = driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
    for i in place:
        Place.append(i.text.split('-')[-1])
except NoSuchElementException:
    Place.append('-')
time.sleep(1)

try:
    dat = driver.find_elements_by_xpath("//h5[@class='ng-binding']")
    for i in dat:
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
time.sleep(1)

try:
    tim = driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")
    for i in tim:
        Time.append(i.text)
except NoSuchElementException:
    Time.append('-')
time.sleep(1)

# Make dataframe
prod_df = pd.DataFrame({'Title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time':Time})
prod_df

,Title,Series,Place,Date,Time
0,5th ODI,INDIA WOMEN TOUR OF NEW ZEALAND ODI SERIES 2022,"John Davies Oval, Queenstown",24 FEB 2022,3:30 AM IST
1,1st T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022,Bharat Ratna Shri Atal Bihari Vajpayee Ekana ...,24 FEB 2022,7:00 PM IST
2,2nd T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Himachal Pradesh Cricket Association Stadium,...",26 FEB 2022,7:00 PM IST
3,3rd T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Himachal Pradesh Cricket Association Stadium,...",27 FEB 2022,7:00 PM IST
4,1st Test,SRI LANKA TOUR OF INDIA TEST SERIES 2022,"Punjab Cricket Association IS Bindra Stadium,...",4 MAR 2022,9:30 AM IST
5,1st ODI,ICC WOMENS WORLD CUP 2022,"Bay Oval, Mount Maunganui",6 MAR 2022,6:30 AM IST
6,2nd ODI,ICC WOMENS WORLD CUP 2022,"Seddon Park, Hamilton",10 MAR 2022,6:30 AM IST
7,2nd Test,SRI LANKA TOUR OF INDIA TEST SERIES 2022,"M Chinnaswamy Stadium, Bengaluru",12 MAR 2022,12:30 PM IST

### 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [48]:
# Activating the chrome browser
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)

# Opening the homepage of Amazon.in
url = "https://www.guru99.com/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [49]:
click_button = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a")       # Locating search_button by xpath
click_button.click()# Clicking the button to start search

In [50]:
click_button2 = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a")       # Locating search_button by xpath
click_button2.click()# Clicking the button to start search

In [51]:
Name = []
Description = []
try:
    nam = driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in nam:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
time.sleep(1)

try:
    description = driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in description:
        Description.append(i.text)
except NoSuchElementException:
    Description.append('-')
time.sleep(1)

# Make dataframe
prod_df = pd.DataFrame({'Name':Name,'Description':Description})
prod_df

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command canâ€™t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does nâ€™t sen...

### 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP

D) GSDP

E) Share

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [4]:
# Activating the chrome browser
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)
# Opening the homepage of Amazon.in
url = "http://statisticstimes.com/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [5]:
click_button = driver.find_element_by_xpath("//div[@class='navbar']/div[2]")       # Locating search_button by xpath
click_button.click()# Clicking the button to start search
time.sleep(1)
click_button2 = driver.find_element_by_xpath("//div[@class='navbar']/div[2]/div/a[3]")       # Locating search_button by xpath
click_button2.click()# Clicking the button to start search

In [6]:
click_button3 = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")       # Locating search_button by xpath
click_button3.click()# Clicking the button to start search

In [18]:
Rank = []
State = []
GSDP_Current = []
GSDP_2011 = []
Share = []
GDP = []

try: 
    rank = driver.find_elements_by_xpath("//tr[@class='odd']/td[1] | //tr[@class='even']/td[1]")
    for i in rank:
        Rank.append(i.text)
        Rank = Rank[:33]
except NoSuchElementException:
    Rank.append('-')
time.sleep(1)

try:
    state = driver.find_elements_by_xpath("//tr[@class='odd']/td[2] | //tr[@class='even']/td[2]")
    for i in state:
        State.append(i.text)
        State =State[:33]
except NoSuchElementException:
    State.append('-')
time.sleep(1)

try:
    gsdp_curr = driver.find_elements_by_xpath("//tr[@class='odd']/td[3] | //tr[@class='even']/td[3]")
    for i in gsdp_curr:
        GSDP_Current.append(i.text)
        GSDP_Current =GSDP_Current[:33]
except NoSuchElementException:
    GSDP_Current.append('-')
time.sleep(1)

try:
    gsdp_2011 = driver.find_elements_by_xpath("//tr[@class='odd']/td[7]| //tr[@class='even']/td[7]")
    for i in gsdp_2011:
        GSDP_2011.append(i.text)
        GSDP_2011 =GSDP_2011[:33]
except NoSuchElementException:
    GSDP_2011.append('-')
time.sleep(1)

try:
    share = driver.find_elements_by_xpath("//tr[@class='odd']/td[5] | //tr[@class='even']/td[5]")
    for i in share:
        Share.append(i.text)
        Share =Share[:33]
except NoSuchElementException:
    Share.append('-')
time.sleep(1)

try:
    gdp = driver.find_elements_by_xpath("//tr[@class='odd']/td[6] | //tr[@class='even']/td[6]")
    for i in gdp:
        GDP.append(i.text)
        GDP =GDP[:33]
except NoSuchElementException:
    GDP.append('-')
time.sleep(1)

# Make dataframe
prod_df = pd.DataFrame({'Rank':Rank,'State':State,'GSDP_Current':GSDP_Current,'GSDP_2011':GSDP_2011,'Share':Share,'GDP($billion)':GDP})
prod_df

,Rank,State,GSDP_Current,GSDP_2011,Share,GDP($billion)
0,1,Maharashtra,-,-,13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,312,929",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,166,817",8.39%,240.726
3,4,Gujarat,-,-,7.96%,228.290
4,5,Karnataka,"1,631,977","1,156,039",7.91%,226.806
5,6,West Bengal,"1,253,832","793,223",5.77%,165.556
6,7,Rajasthan,"1,020,989","711,627",4.99%,143.179
7,8,Andhra Pradesh,"972,782","672,018",4.57%,131.083
8,9,Telangana,"969,604","663,258",4.56%,130.791
9,10,Madhya Pradesh,"906,672","561,801",4.29%,122.977
10,11,Kerala,-,-,4.14%,118.733
11,12,Delhi,"856,112","634,408",4.10%,117.703
12,13,Haryana,"831,610","572,240",3.89%,111.519
13,14,Bihar,"611,804","414,977",2.81%,80.562
14,15,Punjab,"574,760","418,868",2.79%,79.957
15,16,Odisha,"521,275","396,499",2.58%,74.098
16,17,Assam,-,-,1.67%,47.982
17,18,Chhattisgarh,"329,180","243,477",1.61%,46.187
18,19,Jharkhand,"328,598","240,036",1.57%,45.145
19,20,Uttarakhand,-,-,1.30%,37.351
20,21,Jammu & Kashmir,-,-,0.83%,23.690
21,22,Himachal Pradesh,"165,472","124,403",0.81%,23.369
22,23,Goa,"80,449","63,408",0.39%,11.115
23,24,Tripura,"55,984","40,583",0.26%,7.571
24,25,Chandigarh,-,-,0.22%,6.397
25,26,Puducherry,"38,253","25,093",0.18%,5.230
26,27,Meghalaya,"36,572","26,695",0.18%,5.086
27,28,Sikkim,"32,496","20,017",0.15%,4.363
28,29,Manipur,"31,790","20,673",0.15%,4.233
29,30,Nagaland,-,-,0.14%,4.144
30,31,Arunachal Pradesh,-,-,0.13%,3.737
31,32,Mizoram,"26,503","18,797",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

### 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used ASSIGNMENT

Note: - From the home page you have to click on the trending option from Explore menu through code

In [3]:
# Activating the chrome browser
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)
# Opening the homepage of Amazon.in
url = "https://github.com/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [4]:
click_explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")       # Locating search_button by xpath
click_explore.click()
click_trending = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")       # Locating search_button by xpath
click_trending.click() # Clicking the button to start search

In [5]:
# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2) 

    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
    #scraping repositories discription
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,Anduin2017 / HowToCook,-,121,[No languages used]
1,commaai / openpilot,-,280,"[Python, C++, C, Cython, MATLAB, Shell]"
2,withfig / autocomplete,-,182,[TypeScript]
3,doocs / advanced-java,-,31,"[Java, JavaScript]"
4,BySergeyDev / NvidiaRTX-LHRv2Unlocker,-,No details available,[No languages used]
5,labuladong / fucking-algorithm,-,97,[Markdown]
6,J0hnbX / RedTeam-Resources,-,3,[Python]
7,danistefanovic / build-your-own-x,-,72,[No languages used]
8,vvmdx / Sec-Interview-4-2023,-,No details available,[No languages used]
9,coding-horror / basic-computer-games,-,158,"[C#, JavaScript, Java, Python, Perl, BASIC]"
10,zadam / trilium,-,58,"[JavaScript, CSS, EJS, Shell, Dockerfile, HTML]"
11,automerge / automerge,-,57,"[JavaScript, TypeScript]"
12,danielbeach / data-engineering-practice,-,No details available,"[Python, Dockerfile]"
13,netdata / netdata,-,496,"[C, Python, JavaScript, Shell, CSS, HTML]"
14,NVlabs / instant-ngp,-,10,"[Cuda, C++, Python, CMake, C, Dockerfile]"
15,rui314 / mold,-,34,"[C++, Shell]"
16,iperov / DeepFaceLive,-,2,[Python]
17,tiangolo / fastapi,-,294,[Python]
18,cat-milk / Anime-Girls-Holding-Programming-Books,-,166,[No languages used]
19,hasura / graphql-engine,-,415,"[Haskell, TypeScript, JavaScript, Go, Python, ..."
20,ant-design / pro-components,-,421,"[TypeScript, Less, JavaScript]"
21,aquasecurity / cloudsploit,-,63,[JavaScript]
22,cube0x0 / BofRoast,-,No details available,"[C, Python, Makefile]"
23,cosmtrek / air,-,33,"[Go, Shell, Makefile]"
24,OpenZeppelin / openzeppelin-contracts,-,307,"[JavaScript, Solidity, Ruby]"

### 6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [6]:
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)
# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)

In [7]:
charts=driver.find_element_by_xpath("//a[@class='c-link  lrv-a-unstyle-link a-font-primary-bold lrv-u-font-size-28@desktop-xl lrv-u-font-size-18 lrv-u-color-grey:hover u-padding-a-1@desktop-max lrv-u-padding-b-050']")
charts.click()

In [9]:
hot_100 = driver.find_element_by_xpath("//span[@class='c-span  a-font-primary-bold-m lrv-u-color-white lrv-u-text-align-center u-font-size-17 u-line-height-120 a-truncate-ellipsis-2line lrv-u-padding-lr-050']")
hot_100.click()

In [58]:
#scraping song names
song_name = []
try:
    names=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-padding-l-050 lrv-u-padding-l-1@mobile-max']/h3 | //li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light  lrv-u-padding-l-1@mobile-max']/h3")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('-')
time.sleep(2)    
#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-padding-l-050 lrv-u-padding-l-1@mobile-max']/span | //li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light  lrv-u-padding-l-1@mobile-max']/span ")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('-')
time.sleep(2)
    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max'][1]/span")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('-') 
time.sleep(2)

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']/span")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('-')
time.sleep(2)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']/span")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('-')
time.sleep(2)

weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max'][2]/span")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('-')
time.sleep(2)
print(len(song_name),len(artist_name),len(last_week_rank),len(peak_rank),len(weeks))

Songs=pd.DataFrame({"SONG NAME":song_name,
                   "ARTIST":artist_name,
                   "LAST WEEK RANK":last_week_rank,
                   "PEAK RANK":peak_rank,
                   "WEEK ON BOARD":weeks})
Songs

100 100 100 100 100

,SONG NAME,ARTIST,LAST WEEK RANK,PEAK RANK,WEEK ON BOARD
0,We Don't Talk About Bruno,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenz...",1,1,8
1,Heat Waves,Glass Animals,4,2,57
2,Easy On Me,Adele,3,1,19
3,abcdefu,GAYLE,7,4,13
4,Stay,The Kid LAROI & Justin Bieber,5,1,32
...,...,...,...,...,...
95,All Too Well (Taylor's Version),Taylor Swift,84,1,14
96,Come Back As A Country Boy,Blake Shelton,89,85,5
97,Iffy,Chris Brown,96,71,5
98,Home Sweet,Russell Dickerson,94,88,5
99,Too Easy,Gunna & Future,92,16,16

## 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [64]:
driver=webdriver.Chrome("E:\Data science\FLIPROBO\web driver\chromedriver.exe") 
time.sleep(3)
# Opening the billboard
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)
driver.maximize_window()

In [66]:
from bs4 import BeautifulSoup

In [67]:

#clicking on recruiters link
recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

#scrapping names
name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:           #handling no such element exception
    name.append('No details available')
time.sleep(2)


#scrapping designation
designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:        #handling no such element exception
    designation.append('No details available')
time.sleep(2)


#scrapping company names
company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:#handling no such element exception
    company.append('No details available')
time.sleep(2)

#scrapping location names
location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

#skills they hire for
skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:        #handling no such element exception
    skill.append('No details available')
time.sleep(2)    
        
#creating dataframe
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills I hire':skill})
df

,Name,Designation,Company,Location,Skills I hire
0,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
5,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
11,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
12,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
13,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
14,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
15,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
16,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
17,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
18,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
19,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
20,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
21,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
25,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
28,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
29,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
30,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
31,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
32,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
33,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
34,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
35,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
36,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
37,Amir Chowdhury,Managing Partner,Granular.ai,No details available,"Machine Learning, Data Science, Product Manage..."
38,Radha Manivasagam,HR Executive,Techcovery,Bengaluru / Bangalore,"Python, Artificial Intelligence, Machine Learn..."
39,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
41,Sagar Lama,Company HR Manager,AdView,Bengaluru / Bangalore,"Full Stack Developers, Product Manager, Data S..."
42,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
43,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
44,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
45,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
46,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
47,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
48,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
49,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."

### 8. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

#scrapping book names
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scrapping author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)    

#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scrapping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

## 9. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

    You have to find the following details:

        A) Name

        B) Year span

        C) Genre

        D) Run time

        E) Ratings

        F) Votes

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)


# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
time.sleep(2)


# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)


# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
time.sleep(2)


# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
time.sleep(2)

# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

## 10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df